---
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    uses: voxpupuli/gha-puppet/.github/workflows/release.yml@v2
    with:
      allowed_owner: 'ttousai'
    secrets:
      # Configure secrets here:
      #  https://docs.github.com/en/actions/security-guides/encrypted-secrets
      username: ${{ secrets.PUPPET_FORGE_USERNAME }}
      api_key: ${{ secrets.PUPPET_FORGE_API_KEY }}